import fs from "fs";
import path from "path";
import { ConfigValidationError } from "./errors.js";
import {
  assignCoercedTargetLocales,
  coerceTargetLocalesField,
  normalizeLocale,
  parseLocaleList,
} from "./locale-utils.js";
import type { I18nConfig, RawI18nConfigInput } from "./types.js";

/**
 * UI language manifest (`ui-languages.json`).
 * Drives language switcher labels and, when configured, which locales receive UI string translation.
 */
export interface UiLanguageEntry {
  code: string;
  /**
   * Language name **in that language** (endonym), for in-app menus and switchers - e.g. `Deutsch`, `日本語`.
   * Not necessarily English.
   */
  label: string;
  /** English (or Latin-script) name for LLM prompts, `t()` keys, and pairing with `label` in menus. Required in the JSON manifest. */
  englishName: string;
  /** Text direction for layout / `dir` (see `getTextDirection`). Required in `ui-languages.json`. */
  direction: "ltr" | "rtl";
}

/** True if a string looks like a file path (not a BCP-47 locale code). */
export function looksLikeUiLanguagesFileRef(s: string): boolean {
  const t = s.trim();
  if (!t) {
    return false;
  }
  if (t.endsWith(".json")) {
    return true;
  }
  if (t.includes("/") || t.includes("\\")) {
    return true;
  }
  return false;
}

/**
 * Reject `targetLocales` entries that look like paths to `ui-languages.json`; locales must be listed as codes.
 * `ui-languages.json` is generated by `extract` / `generate-ui-languages`, not read for config.
 */
export function assertTargetLocalesAreLocaleCodes(targetLocales: string[], fieldLabel: string): void {
  for (const t of targetLocales) {
    if (looksLikeUiLanguagesFileRef(t)) {
      throw new ConfigValidationError(
        `${fieldLabel} must list BCP-47 locale codes only, not a path to a JSON file. ` +
          "Set `uiLanguagesPath` for where `ui-languages.json` is written; run `extract` to regenerate it."
      );
    }
  }
}

/**
 * Coerce `targetLocales` to an array and ensure entries are locale codes (not manifest paths).
 * Call on merged config input **before** {@link parseI18nConfig} (e.g. from {@link loadI18nConfigFromFile}).
 */
export function expandTargetLocalesFileReferenceInRawInput(
  raw: RawI18nConfigInput,
  _cwd: string
): void {
  assignCoercedTargetLocales(raw);
  const locs = raw.targetLocales;
  if (!Array.isArray(locs)) {
    return;
  }
  assertTargetLocalesAreLocaleCodes(locs, "targetLocales");
}

/**
 * Coerce each documentation block's `targetLocales` and ensure entries are locale codes only.
 */
export function expandDocumentationTargetLocalesInRawInput(
  raw: RawI18nConfigInput,
  _cwd: string
): void {
  const docs = raw.documentations;
  if (!Array.isArray(docs)) {
    return;
  }
  for (const item of docs) {
    if (!item || typeof item !== "object" || Array.isArray(item)) {
      continue;
    }
    const d = item as Record<string, unknown>;
    const tl = d.targetLocales;
    if (tl === undefined || tl === null) {
      continue;
    }
    const arr = coerceTargetLocalesField(tl);
    d.targetLocales = arr;
    assertTargetLocalesAreLocaleCodes(arr, "documentations[].targetLocales");
  }
}

/**
 * Locale codes used for **documentation** translation (markdown / JSON): union of each block's
 * `targetLocales` when non-empty, otherwise root `targetLocales`, per block. Excludes `sourceLocale`, deduped.
 */
export function getDocumentationTargetLocaleCodes(config: I18nConfig): string[] {
  const src = normalizeLocale(config.sourceLocale);
  const seen = new Set<string>();
  const out: string[] = [];
  for (const block of config.documentations) {
    const doc = block.targetLocales;
    const useDoc = Array.isArray(doc) && doc.length > 0;
    const list = useDoc ? doc! : config.targetLocales;
    for (const l of list) {
      const c = normalizeLocale(l);
      if (c === src || seen.has(c)) {
        continue;
      }
      seen.add(c);
      out.push(c);
    }
  }
  return out;
}

/**
 * Locales for `translate` / `sync` document steps (and `status` markdown columns). Honors `--locale` by
 * intersecting with allowed documentation targets.
 */
export function resolveLocalesForDocumentation(
  config: I18nConfig,
  _cwd: string,
  cliLocalesRaw?: string | null
): string[] {
  const base = getDocumentationTargetLocaleCodes(config);
  const src = normalizeLocale(config.sourceLocale);
  if (cliLocalesRaw?.trim()) {
    const requested = parseLocaleList(cliLocalesRaw).map((c) => normalizeLocale(c));
    const allowed = new Set(base);
    const list = requested.filter((c) => c !== src && allowed.has(c));
    if (list.length === 0 && requested.filter((c) => c !== src).length > 0) {
      throw new Error(
        `[translate] None of the requested --locale codes are documentation target locales. Allowed: ${[...allowed].join(", ") || "(none)"}`
      );
    }
    return list;
  }
  return base;
}

/**
 * Locales for `translate-svg`: always includes `sourceLocale` (copy-through output), plus documentation
 * target locales (same as {@link getDocumentationTargetLocaleCodes}).
 */
export function resolveLocalesForSvg(
  config: I18nConfig,
  _cwd: string,
  cliLocalesRaw?: string | null
): string[] {
  const docTargets = getDocumentationTargetLocaleCodes(config);
  const src = normalizeLocale(config.sourceLocale);
  const base: string[] = [src];
  for (const l of docTargets) {
    if (!base.includes(l)) {
      base.push(l);
    }
  }
  if (cliLocalesRaw?.trim()) {
    const requested = parseLocaleList(cliLocalesRaw).map((c) => normalizeLocale(c));
    const allowed = new Set(base);
    const list = requested.filter((c) => allowed.has(c));
    if (list.length === 0 && requested.length > 0) {
      throw new Error(
        `[translate-svg] None of the requested --locale codes are allowed. Allowed: ${[...allowed].join(", ")}`
      );
    }
    return list;
  }
  return base;
}

export function resolveUiLanguagesAbsPath(config: I18nConfig, cwd: string): string | null {
  const p = config.uiLanguagesPath?.trim();
  if (!p) {
    return null;
  }
  return path.isAbsolute(p) ? p : path.join(cwd, p);
}

export function loadUiLanguageEntries(absPath: string): UiLanguageEntry[] {
  const raw = fs.readFileSync(absPath, "utf8");
  const data = JSON.parse(raw) as unknown;
  if (!Array.isArray(data)) {
    throw new Error(
      "ui-languages.json must be a JSON array of { code, label, englishName, direction }"
    );
  }
  const out: UiLanguageEntry[] = [];
  for (const item of data) {
    if (item === null || typeof item !== "object") {
      continue;
    }
    const o = item as Record<string, unknown>;
    const code = typeof o.code === "string" ? o.code.trim() : "";
    if (!code) {
      continue;
    }
    const label = typeof o.label === "string" ? o.label : code;
    const enRaw = o.englishName;
    if (typeof enRaw !== "string" || !enRaw.trim()) {
      throw new Error(
        `ui-languages.json: entry with code "${code}" must include a non-empty string "englishName"`
      );
    }
    const englishName = enRaw.trim();
    const dirRaw = o.direction;
    if (dirRaw !== "ltr" && dirRaw !== "rtl") {
      throw new Error(
        `ui-languages.json: entry with code "${code}" must include "direction": "ltr" or "rtl"`
      );
    }
    const direction = dirRaw;
    out.push({ code, label, englishName, direction });
  }
  if (out.length === 0) {
    throw new Error("ui-languages.json: no valid entries with a `code` field");
  }
  return out;
}

/** Merge `englishName` into `localeDisplayNames` (normalized locale keys) for LLM prompts. */
export function mergeUiLanguageDisplayNames(
  config: I18nConfig,
  entries: UiLanguageEntry[]
): I18nConfig {
  const names = { ...(config.localeDisplayNames ?? {}) };
  for (const e of entries) {
    const n = normalizeLocale(e.code);
    if (!names[n]) {
      names[n] = e.englishName;
    }
  }
  return { ...config, localeDisplayNames: names };
}

/**
 * Codes from `ui-languages.json` that are not the config source locale.
 * If `config.targetLocales` is non-empty, keep only codes present in both (subset for apps that ship fewer translations).
 */
export function resolveUiTranslationTargetCodes(
  config: I18nConfig,
  entries: UiLanguageEntry[]
): string[] {
  const src = normalizeLocale(config.sourceLocale);
  const fromFile = entries.map((e) => normalizeLocale(e.code)).filter((c) => c !== src);

  const configured = config.targetLocales.map((l) => normalizeLocale(l));
  if (configured.length === 0) {
    return fromFile;
  }
  const allowed = new Set(fromFile);
  return configured.filter((c) => allowed.has(c));
}

/**
 * Locales for `translate-ui` (and the UI step of `translate` / `sync`).
 * Uses root `targetLocales` (minus `sourceLocale`). With `--locale`, keeps only codes in that set.
 */
export function resolveLocalesForUI(
  config: I18nConfig,
  _cwd: string,
  cliLocalesRaw?: string | null
): string[] {
  const src = normalizeLocale(config.sourceLocale);
  const allowed = new Set(config.targetLocales.map((l) => normalizeLocale(l)));

  let list: string[];
  if (cliLocalesRaw?.trim()) {
    list = parseLocaleList(cliLocalesRaw).map((c) => normalizeLocale(c));
    const before = list.length;
    list = list.filter((c) => allowed.has(c));
    if (list.length === 0 && before > 0) {
      throw new Error(
        `[translate-ui] None of the requested locales appear in targetLocales. Allowed: ${[...allowed].join(", ")}`
      );
    }
  } else {
    list = [...allowed];
  }

  return list.filter((c) => normalizeLocale(c) !== src);
}
